# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbbf6840817820f0e125f1516882df58033371b9632a5b1b4bdb676a6eee23eb6b0146923b42f33eeb428d3d5814fdbff79374b7586f6a25a4ca075d091d5db

test:
  secret_key_base: cc71f3e44d09dadf07aeae9d5a7831c461be0b102a88124fabf3834a852ac7496e67a6f550a9d4818d60797aa089b5e6e6630cc6cd074b6d1cc2cc455ddf6fc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
